// Cricket Simulation Constants
// ===========================================

// Match Configuration
const MATCH_CONFIG = {
  OVERS_PER_INNINGS: 20,
  BALLS_PER_OVER: 6,
  MAX_WICKETS: 10,
  MIN_SQUAD_SIZE: 11,
  MAX_SQUAD_SIZE: 12,
  WIDE_RUNS: 1,
  NO_BALL_RUNS: 1,
  SUPER_OVER_BALLS: 6,
  SUPER_OVER_MAX_WICKETS: 2,
};

// Tournament Configuration
const TOURNAMENT_CONFIG = {
  MIN_TEAMS: 2,
  LEAGUE_MATCHES_PER_TEAM: 18, // 9 home, 9 away
  PLAYOFF_TEAMS: 4,
  POINTS_WIN: 2,
  POINTS_TIE: 1,
  POINTS_LOSS: 0,
  API_TIMEOUT_MS: 30000,
};

// Player Skill Ranges
const SKILL_RANGES = {
  MIN_RATING: 0,
  MAX_RATING: 100,
  NEUTRAL_LUCK: 75,
  DEFAULT_BAT_RATING: 60,
  DEFAULT_BOWL_RATING: 60,
  ELITE_RATING: 85,
  STRONG_RATING: 80,
  WEAK_RATING: 50,
};

// Team Strength Multipliers
const TEAM_STRENGTH = {
  MASSIVE_ADVANTAGE: 20,
  STRONG_ADVANTAGE: 12,
  MODERATE_ADVANTAGE: 6,
  DOMINANT_MULTIPLIER: 1.2, // Reduced from 1.5 for closer matches
  UPSET_CHANCE_LEAGUE: 0.10,
  UPSET_CHANCE_PLAYOFFS: 0.15, // Increased from 0.05 for more upsets
  UPSET_MULTIPLIER_LEAGUE: 1.20,
  UPSET_MULTIPLIER_PLAYOFFS: 1.25, // Increased from 1.15 for competitive balance
};

// Phase Configuration
const PHASE_CONFIG = {
  POWERPLAY_OVERS: 6,
  MID_OVERS_END: 15,
  DEATH_OVERS_START: 16,
  EARLY_COLLAPSE_OVERS: 4,
  SET_BATTER_BALLS: 10,
  SETTLED_BATTER_BALLS: 20,
  PARTNERSHIP_MILESTONES: [20, 50, 80, 120],
  NERVOUS_NINETIES_RANGE: [90, 100],
  NERVOUS_EIGHTIES_RANGE: [80, 90],
  MILESTONE_RUNS: [49, 74],
};

// Fatigue and Pressure
const FATIGUE_CONFIG = {
  BOWLER_FATIGUE_OVERS: [3, 4],
  DEATH_FATIGUE_OVERS: 2,
  FATIGUE_PENALTY_PER_LEVEL: 0.05,
  CONSECUTIVE_DOTS_PRESSURE: 3,
  MAX_PRESSURE_PENALTY: 6,
  COLLAPSE_WICKETS: 3,
  TAIL_START_WICKETS: 6,
};

// Venue and Pitch Effects
const VENUE_CONFIG = {
  BOUNDARY_SIZES: ['tiny', 'small', 'medium', 'large'],
  PITCH_TYPES: ['flat', 'green', 'dusty', 'slow'],
  CHASE_PROBABILITY_THRESHOLD: 0.6,
  SPN_FRIENDLY_THRESHOLD: 0.7,
  DEW_FACTOR_CHANCE: 0.25,
  HUGE_TARGET: 200,
  HIGH_CHASE_RATE: 14,
  MODERATE_CHASE_RATE: 12,
  AGGRESSIVE_CHASE_RATE: 11,
  CONTROLLED_CHASE_RATE: 9,
  CONSERVATIVE_CHASE_RATE: 6.5,
  VERY_CONSERVATIVE_CHASE_RATE: 5,
};

// Multipliers and Boosts
const MULTIPLIERS = {
  LUCK_VARIANCE: 0.30,
  LUCK_MIN_MULTIPLIER: 0.85,
  LUCK_MAX_MULTIPLIER: 1.15,
  STAR_PLAYER_VARIANCE: 0.15,
  STAR_PLAYER_MIN_MULTIPLIER: 0.95,
  SIGHT_BONUS_10_BALLS: 1.06,
  SIGHT_BONUS_25_BALLS: 1.12,
  PARTNERSHIP_BONUS_40_RUNS: 1.05,
  PARTNERSHIP_BONUS_75_RUNS: 1.08,
  LEADERSHIP_BOOST: 1.05,
  DEW_BOWLER_PENALTY: 0.95,
  DEFEND_PRESSURE_BOOST: 1.10,
  ANCHOR_RESILIENCE_MAX: 3,
  ANCHOR_SKILL_BOOST_MAX: 0.12,
  ANCHOR_SETTLED_BOOST: 0.05,
  ANCHOR_FORTRESS_BOOST: 0.08,
  ANCHOR_CLUTCH_BOOST: 0.10,
};

// Weight Adjustments
const WEIGHT_ADJUSTMENTS = {
  POWERPLAY_SIX_BONUS: 2,
  POWERPLAY_FOUR_BONUS: 1,
  DEATH_SIX_BONUS: 2,
  DEATH_FOUR_BONUS: 1,
  TINY_BOUNDARY_SIX_BONUS: 4,
  TINY_BOUNDARY_FOUR_BONUS: 3,
  LARGE_BOUNDARY_SINGLE_BONUS: 2,
  LARGE_BOUNDARY_DOUBLE_BONUS: 2,
  LARGE_BOUNDARY_TRIPLE_BONUS: 1,
  SPIN_WICKET_BONUS: 2,
  SPIN_DOT_BONUS: 1,
  SPIN_SIX_PENALTY: 1,
  MYSTERY_WICKET_BONUS: 3,
  MYSTERY_FOUR_BONUS: 2,
  MYSTERY_SIX_BONUS: 1,
  YORKER_WICKET_BONUS: 2,
  EXPRESS_PACE_SIX_BONUS: 2,
  EXPRESS_PACE_WICKET_BONUS: 1,
  CONTROL_DOT_BONUS: 3,
  CONTROL_FOUR_PENALTY: 2,
  CONSECUTIVE_DOTS_SIX_BONUS: 2,
  CONSECUTIVE_DOTS_FOUR_BONUS: 1,
  CONSECUTIVE_DOTS_WICKET_BONUS: 0.8,
  SETTLED_BATTER_SIX_BONUS: 2,
  SETTLED_BATTER_FOUR_BONUS: 3,
  NEW_BATTER_DOT_BONUS: 4,
  NEW_BATTER_FOUR_PENALTY: 2,
  NEW_BATTER_SIX_PENALTY: 2,
  TAIL_WICKET_BONUS: 3,
  TAIL_DEATH_SIX_BONUS: 4,
  TAIL_DEATH_WICKET_BONUS: 2,
};

// Minimum Wicket Rates
const MIN_WICKET_RATES = {
  BASE_LEAGUE: 3.0, // Reduced from 4.0 for fewer all-outs
  BASE_PLAYOFFS: 2.8, // Reduced from 3.5 for competitive playoffs
  DUSTY_PITCH_LEAGUE: 4.0, // Reduced from 5.0
  DUSTY_PITCH_PLAYOFFS: 3.5, // Reduced from 4.5
  SLOW_PITCH_LEAGUE: 4.0, // Reduced from 5.0
  SLOW_PITCH_PLAYOFFS: 3.5, // Reduced from 4.5
  GREEN_PITCH_LEAGUE: 4.5, // Reduced from 5.5
  GREEN_PITCH_PLAYOFFS: 3.8, // Reduced from 4.5
  POWERPLAY_LEAGUE: 2.5, // Reduced from 3.5
  POWERPLAY_PLAYOFFS: 2.0, // Reduced from 3.0
  WEAK_TEAM_COLLAPSE_BONUS: 2.0, // Reduced from 3.0
  
  // New realistic limits
  MAX_WICKETS_PER_OVER: 2.0, // Max 2 wickets per over
  MIN_BALLS_PER_WICKET: 6.0, // Minimum 6 balls between wickets
  WEAK_TEAM_PROTECTION: 0.7, // 30% reduction for weak teams
  STRONG_BOWLING_PENALTY: 0.8, // 20% reduction for very strong bowling
};

// Form and Confidence
const FORM_CONFIG = {
  HIGH_STRIKE_RATE: 160,
  LOW_STRIKE_RATE: 100,
  FORM_INCREMENT: 0.05,
  FORM_DECREMENT: 0.05,
  MAX_FORM: 1.25,
  MIN_FORM: 0.75,
  BOWLING_FORM_WKTS_THRESHOLD: 2,
  BOWLING_FORM_RUNS_THRESHOLD: 50,
  BOWLING_FORM_INCREMENT: 0.05,
  BOWLING_FORM_DECREMENT: 0.05,
  BOWLING_MAX_FORM: 1.2,
  BOWLING_MIN_FORM: 0.8,
  CONFIDENCE_WICKET_BOOST: 0.05,
  CONFIDENCE_BOUNDARY_DROP_SIX: 0.08,
  CONFIDENCE_BOUNDARY_DROP_FOUR: 0.04,
  CONFIDENCE_DOT_GAIN: 0.01,
  CONFIDENCE_MIN: 0.8,
  CONFIDENCE_MAX: 1.2,
};

// Awards Thresholds
const AWARDS_CONFIG = {
  MIN_BALLS_FOR_SR: 30,
  MIN_BALLS_FOR_ECONOMY: 24,
  IMPACT_RUNS_MULTIPLIER: 1,
  IMPACT_WKTS_MULTIPLIER: 25,
  IMPACT_SIXES_MULTIPLIER: 2,
};

// Error Messages
const ERROR_MESSAGES = {
  NEED_MIN_TEAMS: "Need at least 2 teams to simulate.",
  MISSING_API_KEY: "Gemini API Key is missing!",
  API_TIMEOUT: "Gemini API request timed out",
  NETWORK_ERROR: "Network error: ",
  PARSE_ERROR: "Failed to parse Gemini API response: ",
  BOTH_SIMULATIONS_FAILED: "Both AI and Local Simulation Failed",
  NO_RESPONSE_CANDIDATES: "No response candidates from Gemini API",
};

module.exports = {
  MATCH_CONFIG,
  TOURNAMENT_CONFIG,
  SKILL_RANGES,
  TEAM_STRENGTH,
  PHASE_CONFIG,
  FATIGUE_CONFIG,
  VENUE_CONFIG,
  MULTIPLIERS,
  WEIGHT_ADJUSTMENTS,
  MIN_WICKET_RATES,
  FORM_CONFIG,
  AWARDS_CONFIG,
  ERROR_MESSAGES,
};
